# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       qtest-qml

# >> macros
# << macros

Summary:    Unit test framework for QML
Version:    0
Release:    1
Group:      System/Libraries
License:    LGPL v.2.1
URL:        http://qt.gitorious.org/qt-labs/qtest-qml
Source0:    %{name}-%{version}.tar.bz2
Source100:  qtest-qml.yaml
Patch0:     0001-Don-t-destroy-qApp-if-it-s-created-outside-of-quick_.patch
Patch1:     0002-load-translations.patch
Requires:   qt4-default
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(QtCore) >= 4.7.1
BuildRequires:  pkgconfig(QtDeclarative)
BuildRequires:  pkgconfig(QtOpenGL)

%description
Qt Labs Unit test framework for QML

%package devel
Summary:    Development files for integrating with QML Unit test runner
Group:      Development/Tools
Requires:   %{name} = %{version}-%{release}

%description devel
Development files for integrating test apps with QML Unit test runner


%prep
%setup -q -n %{name}-%{version}/%{name}

# 0001-Don-t-destroy-qApp-if-it-s-created-outside-of-quick_.patch
%patch0 -p1
# 0002-load-translations.patch
%patch1 -p1
# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake 

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake_install

# >> install post
# << install post

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
%{_libdir}/libQtQuickTest.so.*
%{_libdir}/qt4/imports/QtQuickTest/*
%{_libdir}/qt4/bin/qmltestrunner
# >> files
# << files

%files devel
%defattr(-,root,root,-)
%{_includedir}/qt4/QtQuickTest/*
%{_datadir}/qt4/mkspecs/features/qmltestcase.prf
%{_libdir}/libQtQuickTest.so
# >> files devel
# << files devel
